export const dummyUsers = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    created_at: "2024-01-01",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "3",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "4",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "5",
    name: "John Doe",
    email: "john@example.com",
    created_at: "2024-01-01",
  },
  {
    id: "6",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "7",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "8",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "9",
    name: "John Doe",
    email: "john@example.com",
    created_at: "2024-01-01",
  },
  {
    id: "10",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "11",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "12",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
];

export const dummyMicroNano = [
  {
    id: "1",
    micro_sensor: "1",
    micro_motor: "1",
    email: "john@example.com",
    created_at: "2024-01-01",
  },
  {
    id: "2",
    micro_sensor: "1",
    micro_motor: "1",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "3",
    micro_sensor: "1",
    micro_motor: "1",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "4",
    micro_sensor: "1",
    micro_motor: "1",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "5",
    micro_sensor: "1",
    micro_motor: "1",
    name: "John Doe",
    email: "john@example.com",
    created_at: "2024-01-01",
  },
  {
    id: "6",
    micro_sensor: "1",
    micro_motor: "1",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "7",
    micro_sensor: "1",
    micro_motor: "1",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "8",
    micro_sensor: "1",
    micro_motor: "1",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "9",
      micro_sensor: "1",
    micro_motor: "1",
    name: "John Doe",
    email: "john@example.com",
    created_at: "2024-01-01",
  },
  {
    id: "10",
    micro_sensor: "1",
    micro_motor: "1",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "11",
    micro_sensor: "1",
    micro_motor: "1",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
  {
    id: "12",
    micro_sensor: "1",
    micro_motor: "1",
    name: "Jane Smith",
    email: "jane@example.com",
    created_at: "2024-01-05",
  },
];
